const { registerPreprocessor } = require('@riotjs/compiler')
const fs = require('fs');

// register the rust preprocessor
registerPreprocessor('javascript', 'rust', (code, options) => {
  const javascript = options.fragments.javascript
  const { attributes, text } = javascript
  const rustCode = text.text
  const module = attributes.find(a => a.name=='module').value
  writeModuleToFile(module, rustCode)
  const [_, state, dispatch, __, ___, actionEnum ] = rustCode.match(/export!\((\w+), (\w+), (\w+), (\w+), (\w+)\);/)
  //const actions = rustCode.match(/enum (\w+) +{(((\n)?(.*?))+)}/)[2].trim().split(',').filter(x =>!!x).map(x => x.trim())
  console.log(state, dispatch);
  
  return {
    code : `
    import lib from '../Cargo.toml'
    console.log(lib)
    const state = lib.${state}
    const dispatch = lib.${dispatch}
        export default {
            increment(){
                this.update(dispatch(this.state, 'increment'))
            },
            decrement(){
                this.update(dispatch(this.state, 'decrement'))
            },
            double(){
                this.update(dispatch(this.state, 'double'))
            },
            onMounted(){
                this.update(state())
            }
        }
    `
  }
})

module.exports = {
  javascript: 'rs'
} 

function writeModuleToFile(module, code) {
    const stream = fs.createWriteStream(`src/autogenerated/${module}.rs`);
    stream.once('open', function(fd) {
        stream.write(code);
        stream.end();
    });
}
function appendModuleToLib(module) {
    const stream = fs.createWriteStream(`src/autogenerated/mod.rs`, {flags: 'a'});
    stream.once('open', function(fd) {
        stream.write(`\nmod ${module};`);
        stream.end();
    });
}


