#[macro_use]
extern crate stdweb;
#[macro_use]
extern crate serde_derive;

#[macro_use]
mod macros;

mod store;
mod autogenerated;

#[stdweb::js_export]
fn call() {
    let message = "Hello, 世界!";
    js! {
        alert( @{message} );
    }
}
